### PR TITLE
Support Icinga Web 2.4

### LINKED ISSUE #23: Document requirement for Icingaweb2 >= 2.5.0
We need to document the requirement for >= 2.5.0

---
Old content:

Icingaweb2 < 2.5 is missing some joins in `HostgroupQuery` that breaks this module.

```
Cannot join "hoststatus", no such table found

#0 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(837): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->joinVirtualTable('hoststatus')
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(798): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireVirtualTable('hoststatus')
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(754): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->requireColumn('host_handled')
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(1061): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->resolveColumns(Array)
#4 /usr/share/icingaweb2/library/Icinga/Data/SimpleQuery.php(124): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->columns(Array)
#5 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Monitoring/HostgroupsummaryQuery.php(80): Icinga\Data\SimpleQuery->__construct(Object(Icinga\Data\Db\DbConnection), Array)
#6 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Monitoring/HostgroupsummaryQuery.php(129): Icinga\Module\Toplevelview\Monitoring\HostgroupsummaryQuery->createSubQuery('Hostgroup', Array)
#7 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Backend/Ido/Query/IdoQuery.php(703): Icinga\Module\Toplevelview\Monitoring\HostgroupsummaryQuery->joinBaseTables()
#8 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Monitoring/HostgroupsummaryQuery.php(73): Icinga\Module\Monitoring\Backend\Ido\Query\IdoQuery->init()
#9 /usr/share/icingaweb2/library/Icinga/Data/SimpleQuery.php(122): Icinga\Module\Toplevelview\Monitoring\HostgroupsummaryQuery->init()
#10 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Monitoring/HostgroupsummaryQuery.php(22): Icinga\Data\SimpleQuery->__construct(Object(Icinga\Data\Db\DbConnection), Array)
#11 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Monitoring/Hostgroupsummary.php(36): Icinga\Module\Toplevelview\Monitoring\HostgroupsummaryQuery->__construct(Object(Icinga\Data\Db\DbConnection), Array, NULL, true)
#12 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Tree/TLVHostGroupNode.php(54): Icinga\Module\Toplevelview\Monitoring\Hostgroupsummary->__construct(Object(Icinga\Module\Monitoring\Backend\Ido\IdoBackend), Array, NULL, true)
#13 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Tree/TLVTree.php(173): Icinga\Module\Toplevelview\Tree\TLVHostGroupNode::fetch(Object(Icinga\Module\Toplevelview\Tree\TLVTree))
#14 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Tree/TLVTree.php(187): Icinga\Module\Toplevelview\Tree\TLVTree->fetchType('hostgroup')
#15 /usr/share/icingaweb2/modules/toplevelview/library/Toplevelview/Tree/TLVTree.php(230): Icinga\Module\Toplevelview\Tree\TLVTree->ensureFetched()
#16 /usr/share/icingaweb2/modules/toplevelview/application/views/scripts/show/index.phtml(15): Icinga\Module\Toplevelview\Tree\TLVTree->getFetchTime()
#17 /usr/share/icingaweb2/library/Icinga/Web/View.php(233): include('/usr/share/icin...')
#18 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/share/icin...')
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('show/index.phtm...')
#20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('show/index.phtm...', NULL)
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#23 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#24 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#25 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#26 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#27 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#28 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#29 {main}
```

### PR DESCRIPTION
**Pull request by lazyfrosch**
fixes #23

- [x] Fixed Hostgroup queries by embedding
- [ ] Document version dependency to >= 2.4

### CODE REVIEW

**Comment by lazyfrosch** [comment]
@dgoetz this should fix the query, could you test the rest and give me feedback?

**Comment by dgoetz** [comment]
@lazyfrosch Branch was tested and works fine with a very small example config. Thanks!

**Comment by lazyfrosch** [comment]
@dgoetz Grouping has been fixed.

Works for <sup>me</sup>

**Comment by dgoetz** [comment]
@lazyfrosch Count seems correct now. Thanks!

I will try to expand and test configuration even more, but it is only on the nice to have list so other things have higher prio.

**Comment by lazyfrosch** [comment]
Since 2.5.0 is out I decided not to merge this, it is an ugly hack.

Version requirement has been documented in 3a5c23bb7e9f599892da3e2c3235a645e868029c

**Pull request closed without merging**
